Description: >
    Jeferson Rocha / Udacity
    This template deploys a VPC.
Resources:
    UdacityVPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.0.0.0/16
            EnableDnsHostnames: true

